### PR TITLE
Update Zenject to 4.7

### PR DESCRIPTION
**Pull request by SacredSkull**
Updates Zenject to 4.7, including the original PR from @yunspace updating to 4.3.

Here are some especially important change log notes, at least in terms of fixes/improvements with the version in brackets - AKA why you should upgrade: 
 
- Fixed issue for Windows Store platform where zenject was not properly stripping out the WSA generated constructors [4.7] 
- Fix to IL2CPP builds to work again [4.7] 
- Changed Validation to run at edit time rather than requiring that we enter play mode. This is significantly faster. Also added a hotkey to "validate then run" since it's fast enough to use as a pre-run check [4.6] 
- Fixed to ensure that the order that initial instances on the container are injected in follows their dependency order [#161](https://github.com/modesttree/Zenject/issues/161) [4.6] 
- Multiple bug fixes [4.5] 
- Multiple bug fixes [4.4] 

4.3 included the first patches that fixes many of the issues with IL2CPP.

Oh, and yes, the example does in fact run!

### CODE REVIEW

**Comment by cgarciae** [comment]
Thanks @SacredSkull ! Sorry @yunspace for not looking into your pull request.
Have you tested the upgrade? I am currently developing on linux dont have access to a windows environment.

On a side note, I got a question: are you actively using Karma? If you are I apologize for the documentation, there is a bunch of stuff like configuration, pub/sub, etc, that probably is not documented but are really useful.

**Comment by SacredSkull** [comment]
I really only just found Karma, after using a similar framework called [_Unity MVC_](https://bitbucket.org/eduardo_costa/thelab-unity-mvc). Ultimately I found a few major issues with _UMVC_. For example, Controllers inherit from MonoBehaviour, which prevented me from properly testing it. I come from a web development background and am very familar with the concept of routing - the inclusion of a DI is quite a bonus too!

Both of the libraries are pretty young projects, so you don't have to apologize - all _UMVC_ has is [this oxygen site](http://thelaborat.org/unity/mvc/docs/) and a couple of examples. I may add some of my own as I become more used to this framework.

As for testing: all I can say with certainty is the example works as it should. Right now I'm moving an early-stage project from _UMVC_ to Karma, so after I'm done I can probably tell you more.

**Comment by SacredSkull** [comment]
Also, maybe you weren't aware, but Unity now has a beta Linux editor - here's the 5.5 version:

http://beta.unity3d.com/download/59c25c92588f/public_download.html

It's not particularly easy to find! They [post new versions here](https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/) (5.6 is a Unity beta release, 5.5 is stable).

**Comment by cgarciae** [comment]
I'll look into the linux editor! Had no idea about it. 

It would be nice that I had more time to improve the documentation, I also had some experience with web-dev and created Karma because I made an AR app and Unity's scene model wasn't fit for my needs, resulted in very buggy behaviors. 
If you need to do testing the Controller layer is just POCO's so its really fit for that task along with Zenject, in practice you should stabilize your Presenter layer first because you'll get a lot of indirection between the View and the Controller through the Presenter that slows you down a bit.

**Comment by mrserverless** [comment]
hi @cgarciae, I haven't been actively using Karma lately. Was interested in how you've been implementing Zenject. Will revisit this when I get sometime, now that you've also upgraded Zenject to the latest version.

What I have been experimenting on a lot is combining Zenject with UniRx https://github.com/neuecc/unirx which introduces a nice Reactive approach to Unity dev and Microcoroutines. The Zenject folks themselves also recommends it. I think you will like it.

**Pull request merged**
